/** Exact captured local-tool schemas backed by the hash-pinned NativeSandbox. */
import { readFileSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';
const execFileAsync=promisify(execFile);const runner=resolve(dirname(fileURLToPath(import.meta.url)),'../../scripts/run_e97_sandbox_cli.py');
const image=process.env.EMENDER_CLI_IMAGE, imageSha=process.env.EMENDER_CLI_IMAGE_SHA256, python=process.env.EMENDER_PYTHON;
function confined(path:string){if(!path||path.startsWith('/')||path.split('/').includes('..'))throw new Error('path outside Stage-B workspace');return path;}
async function sandbox(argv:string[],cwd:string,signal:AbortSignal,seconds=30){if(!image||!imageSha||!python)throw new Error('Stage-B sandbox authority missing');const args=[runner,'--image',image,'--image-sha256',imageSha,'--cwd',cwd,'--timeout',String(seconds),'--max-output-bytes','16384','--',...argv];const {stdout}=await execFileAsync(python,args,{cwd,env:process.env,timeout:(seconds+10)*1000,maxBuffer:2*1024*1024,signal});const r=JSON.parse(stdout);const text=r.exit_code===0&&!r.timed_out?r.stdout:[r.stdout?.trimEnd(),r.stderr?.trimEnd(),`Command exited with code ${r.exit_code}`].filter(Boolean).join('\n');return{text:String(text??''),isError:Boolean(r.exit_code||r.timed_out),details:r};}
export default function(pi:ExtensionAPI){
 const manifestPath=process.env.E97_PI_TOOL_MANIFEST;if(!manifestPath)throw new Error('tool manifest required');const manifest=JSON.parse(readFileSync(manifestPath,'utf8'));const names=['read','bash','edit','write','process'];const tools=manifest.model_visible_tools.filter((t:any)=>names.includes(t.name));if(tools.map((t:any)=>t.name).join(',')!==names.join(','))throw new Error('Stage-B tool order');const processes=new Map<string,{name:string,text:string,isError:boolean,status:string}>();
 for(const tool of tools)pi.registerTool({name:tool.name,label:tool.label,description:tool.description,parameters:tool.parameters,async execute(_id:string,a:any,signal:AbortSignal,_update:any,ctx:any){
  if(tool.name==='read'){const p=confined(a.path);const start=Number(a.offset??1),limit=Number(a.limit??2000);const code=`import pathlib,sys\np=pathlib.Path(sys.argv[1]);o=int(sys.argv[2]);n=int(sys.argv[3]);lines=p.read_text().splitlines();print('\\n'.join(f'{i}: {v}' for i,v in enumerate(lines[o-1:o-1+n],o)))`;const r=await sandbox(['python','-c',code,p,String(start),String(limit)],ctx.cwd,signal);return{content:[{type:'text',text:r.text.trimEnd()}],details:r.details,isError:r.isError};}
  if(tool.name==='bash'){const r=await sandbox(['bash','-lc',String(a.command)],ctx.cwd,signal,Math.min(120,Number(a.timeout??120)));return{content:[{type:'text',text:r.text}],details:r.details,isError:r.isError};}
  if(tool.name==='edit'){const p=confined(a.path),payload=Buffer.from(JSON.stringify(a.edits)).toString('base64');const code=`import base64,json,pathlib,sys\np=pathlib.Path(sys.argv[1]);e=json.loads(base64.b64decode(sys.argv[2]));s=p.read_text();sp=[]\nfor x in e:\n old=x['oldText']; assert s.count(old)==1, f'expected one exact block, found {s.count(old)}'; i=s.index(old); sp.append((i,i+len(old),x['newText']))\nsp.sort(); assert all(sp[i-1][1]<=sp[i][0] for i in range(1,len(sp)))\nfor a,b,n in reversed(sp): s=s[:a]+n+s[b:]\np.write_text(s);print(f'Successfully replaced {len(e)} block(s) in {p}.')`;const r=await sandbox(['python','-c',code,p,payload],ctx.cwd,signal);return{content:[{type:'text',text:r.text.trimEnd()}],details:r.details,isError:r.isError};}
  if(tool.name==='write'){const p=confined(a.path),payload=Buffer.from(String(a.content)).toString('base64');const code=`import base64,pathlib,sys\np=pathlib.Path(sys.argv[1]);p.parent.mkdir(parents=True,exist_ok=True);d=base64.b64decode(sys.argv[2]);p.write_bytes(d);print(f'Successfully wrote {len(d)} bytes to {p}')`;const r=await sandbox(['python','-c',code,p,payload],ctx.cwd,signal);return{content:[{type:'text',text:r.text.trimEnd()}],details:r.details,isError:r.isError};}
  const action=String(a.action);if(action==='start'){if(a.cwd)confined(a.cwd);const name=String(a.name),id='proc_'+createHash('sha256').update(name+'\0'+String(a.command)).digest('hex').slice(0,8);const r=await sandbox(['bash','-lc',String(a.command)],ctx.cwd,signal,30);processes.set(id,{name,text:r.text,isError:r.isError,status:'finished'});return{content:[{type:'text',text:`Started process ${name} (${id}) with pid 1.`}],details:{id,name,status:'finished'},isError:false};}
  if(action==='output'){const p=processes.get(String(a.id));if(!p)throw new Error('unknown process id');return{content:[{type:'text',text:`"${p.name}" (${a.id}) [${p.status}]\n\nstdout:\n${p.text}`}],details:{id:a.id,status:p.status},isError:p.isError};}
  if(action==='stop'){const p=processes.get(String(a.id));if(!p)throw new Error('unknown process id');p.status='stopped';return{content:[{type:'text',text:`Stopped process ${p.name} (${a.id}).`}],details:{id:a.id,status:p.status}};}
  if(action==='list'){return{content:[{type:'text',text:[...processes].map(([id,p])=>`${id} ${p.name} ${p.status}`).join('\n')}],details:{count:processes.size}};}
  if(action==='clear'){processes.clear();return{content:[{type:'text',text:'Cleared finished processes.'}],details:{count:0}};}
  throw new Error(`unsupported bounded process action ${action}`);
 }});
}
