#!/usr/bin/env python3
"""Fail-closed identity and exposure audit for a nonauthorizing training proposal."""
import argparse,hashlib,json
from pathlib import Path
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def audit(args):
 proposal=json.loads(args.proposal.read_text());root=Path(proposal['preparation_root']);authority=json.loads((root/'manifest.json').read_text());packs=json.loads((root/'packs/manifest.json').read_text());schedule=json.loads((root/'expected-schedule.json').read_text());selected=Path(proposal['selected_curriculum_root'])
 identities=[(proposal['parent_checkpoint'],proposal['parent_checkpoint_sha256']),(root/'manifest.json',proposal['authority_manifest_sha256']),(root/'packs/manifest.json',proposal['pack_manifest_sha256']),(root/'expected-schedule.json',proposal['schedule_sha256']),(selected/'candidate-authority/manifest.json',proposal['selected_authority_sha256']),(selected/'selection-audit.json',proposal['selection_audit_sha256']),(selected/'overlap-audit.json',proposal['overlap_audit_sha256']),('configs/pi/e97-active-tool-surface-v1.json',proposal['tool_manifest_sha256'])]
 if any(sha(path)!=digest for path,digest in identities):raise ValueError('proposal input identity')
 if proposal['schema']!='emender-e97-pi-native-curriculum-training-proposal-v1' or proposal['status']!='frozen-proposal-not-authorized' or proposal['operator_internal_training_authorized'] or proposal['optimizer_updates_authorized'] or proposal['packing_authorized'] or proposal['checkpoint_promotion'] or proposal['automatic_retry'] or proposal['automatic_expansion'] or proposal['new_rl_updates']:raise ValueError('proposal authorization')
 if authority['training_eligible'] or authority['packing_authorized'] or authority['optimizer_updates_authorized'] or packs['training_eligible'] or packs['diagnostic_system_gate']!='cpu-system-gate' or schedule['training_eligible'] or schedule['optimizer_updates_authorized']:raise ValueError('prepared authority authorization')
 if schedule['sampler_key']!=proposal['sampler_key'] or schedule['world_size']!=proposal['data_world_size'] or schedule['context_size']!=proposal['context_size'] or len(schedule['steps'])!=proposal['proposed_updates'] or schedule['source_target_totals']!=proposal['scheduled_source_targets'] or schedule['source_unique_records']!=proposal['scheduled_source_unique_records'] or sum(schedule['source_token_totals'].values())!=proposal['scheduled_input_tokens'] or sum(schedule['source_target_totals'].values())!=proposal['scheduled_assistant_targets'] or schedule['unique_packs']!=proposal['scheduled_unique_packs'] or schedule['unique_records']!=proposal['scheduled_unique_records']:raise ValueError('proposal schedule')
 prior={'conversation':316,'grounded-rehearsal':512,'native':8,'representation-bridge':768,'retention':619}
 if any(schedule['source_unique_records'].get(k)!=v for k,v in prior.items()) or schedule['source_unique_records']['pi-native-curriculum']<1200:raise ValueError('retention/new exposure')
 receipt={'schema':'emender-e97-pi-native-training-proposal-audit-v1','status':'qualified-proposal-not-authorized','proposal_sha256':sha(args.proposal),'parent_checkpoint_sha256':proposal['parent_checkpoint_sha256'],'authority_manifest_sha256':proposal['authority_manifest_sha256'],'pack_manifest_sha256':proposal['pack_manifest_sha256'],'schedule_sha256':proposal['schedule_sha256'],'proposed_updates':proposal['proposed_updates'],'scheduled_input_tokens':proposal['scheduled_input_tokens'],'scheduled_assistant_targets':proposal['scheduled_assistant_targets'],'scheduled_pi_native_records':schedule['source_unique_records']['pi-native-curriculum'],'all_prior_records_once':True,'checker_sha256':sha(__file__),'packing_authorized':False,'optimizer_updates_authorized':0,'checkpoint_promotion':False}
 args.output.write_text(json.dumps(receipt,indent=2,sort_keys=True)+'\n');print('PI_NATIVE_TRAINING_PROPOSAL_AUDIT',sha(args.proposal),sha(args.output))
def main():
 p=argparse.ArgumentParser();p.add_argument('--proposal',type=Path,required=True);p.add_argument('--output',type=Path,required=True);audit(p.parse_args())
if __name__=='__main__':main()
